//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modeller
    {
        public int ModelId { get; set; }
        public string Model { get; set; }
        public Nullable<int> MarkaId { get; set; }
    
        public virtual Markalar Markalar { get; set; }
    }
}
