//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrunBilgiEntities : DbContext
    {
        public UrunBilgiEntities()
            : base("name=UrunBilgiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Markalar> Markalars { get; set; }
        public virtual DbSet<Modeller> Modellers { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<Sectiklerim> Sectiklerims { get; set; }
        public virtual DbSet<Sipari> Siparis { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetays { get; set; }
        public virtual DbSet<Tedarikci> Tedarikcis { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<UrunTuru> UrunTurus { get; set; }
    }
}
